### ISSUE TITLE
Error after starting training

### ISSUE THREAD

**Issue by Sunkua** [mingzhu0527/HAR#2]
Shortly after starting the training the process crashes with the following error:

`Traceback (most recent call last):
  File "matchzoo/main.py", line 359, in <module>
    main(sys.argv)
  File "matchzoo/main.py", line 351, in main
    train(config)
  File "matchzoo/main.py", line 159, in train
    verbose = 1
  File "/usr/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/lib/python3.7/site-packages/keras/engine/training_generator.py", line 215, in fit_generator
    class_weight=class_weight)
  File "/usr/lib/python3.7/site-packages/keras/engine/training.py", line 1443, in train_on_batch
    class_weight=class_weight)
  File "/usr/lib/python3.7/site-packages/keras/engine/training.py", line 795, in _standardize_user_data
    exception_prefix='target')
  File "/usr/lib/python3.7/site-packages/keras/engine/training_utils.py", line 105, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       ...
`
I tried to train the model with the HealthQA-dataset and adjusted my config so the paths point to the prepared HealthQA-dataset-directory.

**Comment by mingzhu0527** [comment]
I just committed a [fix](https://github.com/mingzhu0527/HAR/commit/54eb1002acd9df5faee4c2b52101049f27ad6dd6) to it. Please check it out.

**Comment by Sunkua** [comment]
Everything seems to work now. Thank you :+1:
